name: Continuous Integration

on: push

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: run install and test
        run: |
          npm install
          npm install supertest
          npm install express
          npm install --save-dev vitest
          npm run test

